/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'globalpay';
  static const String PLUGIN_VERSION = '4.2.0+14';
  static const String AGENT = 'assets/icon/agent.svg';
}
